// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Jrko6pEGVYmI-NeceJxsYfRIgllMqLw',
    appId: '1:55757197450:web:2b560c08eb51bc663edd73',
    messagingSenderId: '55757197450',
    projectId: 'syncra-acernity',
    authDomain: 'syncra-acernity.firebaseapp.com',
    storageBucket: 'syncra-acernity.firebasestorage.app',
    measurementId: 'G-GPVLWJS0C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6sxxpH10dJtGOr7mr-lVtAKmSAaZ_HJ4',
    appId: '1:55757197450:android:b932c44b187e84803edd73',
    messagingSenderId: '55757197450',
    projectId: 'syncra-acernity',
    storageBucket: 'syncra-acernity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN2LjDi6uTkq3kBm7XAtSccLM7Z0c0Q2Y',
    appId: '1:55757197450:ios:2bc607b656097b9f3edd73',
    messagingSenderId: '55757197450',
    projectId: 'syncra-acernity',
    storageBucket: 'syncra-acernity.firebasestorage.app',
    iosClientId: '55757197450-16cjhej2j510fnf3jqo6en66a3m0q6is.apps.googleusercontent.com',
    iosBundleId: 'com.vivekupasani.syncra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN2LjDi6uTkq3kBm7XAtSccLM7Z0c0Q2Y',
    appId: '1:55757197450:ios:2bc607b656097b9f3edd73',
    messagingSenderId: '55757197450',
    projectId: 'syncra-acernity',
    storageBucket: 'syncra-acernity.firebasestorage.app',
    iosClientId: '55757197450-16cjhej2j510fnf3jqo6en66a3m0q6is.apps.googleusercontent.com',
    iosBundleId: 'com.vivekupasani.syncra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Jrko6pEGVYmI-NeceJxsYfRIgllMqLw',
    appId: '1:55757197450:web:66f13e3d4b373a883edd73',
    messagingSenderId: '55757197450',
    projectId: 'syncra-acernity',
    authDomain: 'syncra-acernity.firebaseapp.com',
    storageBucket: 'syncra-acernity.firebasestorage.app',
    measurementId: 'G-WZQQ8014FZ',
  );
}
